name: scantrack
description: "ScanTrack - A modern QR & Barcode Scanner app built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # QR & Barcode Scanner
  mobile_scanner: ^5.1.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0

  # Swipe Actions
  flutter_slidable: ^3.1.0

  # Toast Messages
  fluttertoast: ^8.2.4

  # Permission Handling
  permission_handler: ^11.3.1

  # Share Feature
  share_plus: ^7.2.2

  # Modern Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Hive Code Generator
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true